name: utility_app
description: An app that consist common utilities
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: 8.1.2
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  english_words: ^4.0.0
  logger: ^1.4.0
  dartdoc: 6.2.2
  flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

